apiVersion: v2
appVersion: 3.9.0
description: Strimzi Kafka Connect with Debezium Postgres Connector
name: strimzi-kafka-connect
version: 1.1.0
type: application
sources:
  - https://github.com/dkadetov/strimzi-kafka-connect
maintainers:
  - name: dkadetov
dependencies:
  - name: strimzi-kafka-operator
    version: 0.45.0
    repository: oci://quay.io/strimzi-helm
    alias: clusterOperator
    condition: clusterOperator.enabled
