{{- if $.Values.externalConfig.secret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl $.Values.externalConfig.secret.name $ | trunc 63 | trimSuffix "-" | trimSuffix "." | quote }}
  namespace: {{ $.Release.Namespace }}
{{- if .Values.commonLabels }}
  labels: {{- tpl ( toYaml $.Values.commonLabels ) $ | nindent 4 }}
{{- end }}
{{- if .Values.commonAnnotations }}
  annotations: {{- tpl ( toYaml $.Values.commonAnnotations ) $ | nindent 4 }}
{{- end }}
type: {{ tpl ( default "Opaque" $.Values.externalConfig.secret.type ) $ | quote }}
data:
{{- range $key, $value := $.Values.externalConfig.secret.content }}
  {{ $key }}: {{ tpl $value $ | b64enc }}
{{- end }}
{{- end }}
